version: '3.8'

services:
  web:
    build: .
    container_name: panificadorarm_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:SenhaSuperForte123!@db:5432/panificadorarm_db
      - SECRET_KEY=minha_chave_secreta_super_segura_aqui_para_a_panificadora_producao
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: panificadorarm_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SenhaSuperForte123!
      - POSTGRES_DB=panificadorarm_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d panificadorarm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
