### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm


### Criar usuário
POST http://localhost:5000/api/v1/products
Content-Type: application/json

{
  "name": "Pão Doce",
  "unit_price": 1.0,
  "stock": 90
}


### Listar usuários
GET http://localhost:5000/auth/register